version: "3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
      - Eureka
    build: C:\Users\Adam\Desktop\MicroService\MicroserviceProject
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"  }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  Eureka:
     build: C:\Users\Adam\Desktop\MicroService\EurekaMicroservice
     image: eureka
     ports:
      - "8761:8761"
  
  
volumes:
  db:




#version: "2.7.4"
#services:
# 
#
# 
#  maisonhote:
#    container_name: commande
#    build: C:\Users\Adam\Desktop\MicroService\MicroserviceProject
#    ports:
#      - "8081:8081"
#    hostname: commandetest
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/serviceCommande
#      - eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
#    image: "commande"
#    depends_on:
#      - mysql_2
#      - Eureka
# 
#
#   
#  mysql_2:
#    image: "mysql:5.6"
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
#      - MYSQL_DATABASE=serviceCommande
#    ports:
#      - 3308:3306
#     
#  Eureka:
#    build: C:\Users\Adam\Desktop\MicroService\EurekaMicroservice
#    image: eureka
#    ports:
#      - "8761:8761"

#
#
##version: "2.7"
##services:
##
##
##  commande:
##   
##    build: C:\Users\Adam\Desktop\MicroService\MicroserviceProject
##    environment:
##      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
##      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_2:3306/commandeService
##    ports:
##      - "8093:8081"
##    image: "commande"
##    depends_on:
##      - docker-mysql_2
## 
## 
##  docker-mysql_2:
##    image: "mysql:8.0"
##    environment:
##      - MYSQL_ROOT_PASSWORD=root
##      - MYSQL_DATABASE=commandeService
##    ports:
##      - 3308:3306
##  
##  
##   
##  discovery:
##    build: C:\Users\Adam\Desktop\MicroService\EurekaMicroservice
##    ports:
##      - "8761:8761"
##    image: "eureka"
##    
##    
##  